function initializeEquipmentInterfaceDefinitions(tabPointer)

    interfaceDefinitions = interfaceDefinitionManager();
    
    includeDefaultDefinitions = false; % do not remove, the user can modify this in the custom definitions file
    
    % === Add custom definitions to the list:
    backupDefs = interfaceDefinitions;
    try
        % a place for the user to add their own custom equipement definitions:
        custom__interfaceDefinitionsInclude;
    catch
       interfaceDefinitions = backupDefs;
       warning('Could not parse custom interface definitions in ''custom__interfaceDefinitionsInclude.m''. Please check syntax.'); 
    end
    
    % === Add default definitions to the list:
    if(includeDefaultDefinitions)
    
    interfaceDefinitions.add('RS SMA100B Signal Source', ...
        @RS_SMA100B_signalSource_createInterface, ...
        @RS_SMA100B_signalSource_applyChanges);
    
    interfaceDefinitions.add('RS SMA100B Clock Source', ...
        @RS_SMA100B_clockSource_createInterface, ...
        @RS_SMA100B_clockSource_applyChanges);
    
    interfaceDefinitions.add('Keysight B2962A Voltage Source', ...
        @Keysight_B2962A_voltageSource_createInterface, ...
        @Keysight_B2962A_voltageSource_applyChanges);
    
    interfaceDefinitions.add('Keysight B2962A Current Source', ...
        @Keysight_B2962A_currentSource_createInterface, ...
        @Keysight_B2962A_currentSource_applyChanges);
    
    interfaceDefinitions.add('Agilent N6705A Voltage Source', ...
        @Agilent_N6705A_voltageSource_createInterface, ...
        @Agilent_N6705A_voltageSource_applyChanges);
    
    interfaceDefinitions.add('Keithley 2400 Current Source', ...
        @Keithley_2400_currentSource_createInterface, ...
        @Keithley_2400_currentSource_applyChanges);
    
    interfaceDefinitions.add('Keithley 2602B Current Source', ...
        @Keithley_2602B_currentSource_createInterface, ...
        @Keithley_2602B_currentSource_applyChanges);
    
    interfaceDefinitions.add('Keithley 2602B Voltage Source', ...
        @Keithley_2602B_voltageSource_createInterface, ...
        @Keithley_2602B_voltageSource_applyChanges);
    
    interfaceDefinitions.add('Agilent 16902B Logic Analyzer', ...
        @Agilent_16902B_logicAnalyzer_createInterface, ...
        @Agilent_16902B_logicAnalyzer_applyChanges);
    
    interfaceDefinitions.add('Coherent Sampling Module', ...
        @Coherent_sampling_module_createInterface, ...
        @Coherent_sampling_module_applyChanges);

     interfaceDefinitions.add('Agilent E8267D Signal Source', ...
        @Agilent_E8267D_signalSource_createInterface, ...
        @Agilent_E8267D_signalSource_applyChanges);

     interfaceDefinitions.add('Agilent E8267D Clock Source', ...
        @Agilent_E8267D_clockSource_createInterface, ...
        @Agilent_E8267D_clockSource_applyChanges);
    
    end
    
    tabPointer.UserData.interfaceDefinitions = interfaceDefinitions;
    
end