function map_neg = hsadc3c_adc2spi_mapping_neg()
% hsadc3c_adc2spi_mapping_neg Mapping of ADC positive control bit to
%                             SPI bit.
% - INPUTS
%   N.A.
% - OUTPUTS
%   = map_pos: 60*8 = 480 rows x 4 columns cell array containing the mapping
%              - 1st column: SPI register number, integer array
%              - 2nd column: SPI register bit, integer array
%              - 3rd column: control word names, string array
%              - 4th column: control word bit value, binary array

map_neg = {59 7 'In0_n'                            0; ...
           59 6 'In1_n'                            0; ...
           59 5 'In2_n'                            0; ...
           59 4 'NC'                               0; ...
           59 3 'NC'                               0; ...
           59 2 'NC'                               0; ...
           59 1 'NC'                               0; ...
           59 0 'NC'                               0; ...
           
           58 7 'NC'                               0; ...
           58 6 'NC'                               0; ...
           58 5 'NC'                               0; ...
           58 4 'NC'                               0; ...
           58 3 'NC'                               0; ...
           58 2 'NC'                               0; ...
           58 1 'NC'                               0; ...
           58 0 'NC'                               0; ...
           
           57 7 'NC'                               0; ...
           57 6 'NC'                               0; ...
           57 5 'NC'                               0; ...
           57 4 'NC'                               0; ...
           57 3 'NC'                               0; ...
           57 2 'NC'                               0; ...
           57 1 'NC'                               0; ...
           57 0 'D_qcmp1_threshold<12>'            0; ...
           
           56 7 'D_qcmp1_threshold<11>'            0; ...
           56 6 'D_qcmp1_threshold<10>'            0; ...
           56 5 'D_qcmp1_threshold<9>'             0; ...
           56 4 'D_share_dacF_m'                   0; ...
           56 3 'D_qdacF_decreaseRange_m<5>'       0; ...
           56 2 'D_qdacF_decreaseRange_m<4>'       0; ...
           56 1 'D_qdacF_decreaseRange_m<3>'       0; ...
           56 0 'D_qdacF_decreaseRange_m<2>'       0; ...
           
           55 7 'D_qdacF_decreaseRange_m<1>'       0; ...
           55 6 'D_qdacF_decreaseRange_m<0>'       0; ...
           55 5 'D_qdacF_calWord1_m<3>'            0; ...
           55 4 'D_qdacF_calWord1_m<4>'            0; ...
           55 3 'D_qdacF_calWord1_m<5>'            0; ...
           55 2 'D_qdacF_calWord1_m<6>'            0; ...
           55 1 'D_qdacF_calWord1_m<7>'            0; ...
           55 0 'D_qdacF_calWord0_m<0>'            0; ...
           
           54 7 'D_qdacF_calWord0_m<1>'            0; ...
           54 6 'D_qdacF_calWord0_m<2>'            0; ...
           54 5 'D_qdacF_calWord0_m<3>'            0; ...
           54 4 'D_qdacF_calWord0_m<4>'            0; ...
           54 3 'D_qdacF_calWord0_m<5>'            0; ...
           54 2 'D_qdacF_calWord0_m<6>'            0; ...
           54 1 'D_qdacF_calWord0_m<7>'            0; ...
           54 0 'D_fix_precharge'                  0; ...
           
           53 7 'D_hcmp0N_offset_p<0>'             0; ...
           53 6 'D_hcmp0N_offset_p<1>'             0; ...
           53 5 'D_hcmp0N_offset_p<2>'             0; ...
           53 4 'D_hcmp0N_offset_p<3>'             0; ...
           53 3 'D_hcmp0N_offset_p<4>'             0; ...
           53 2 'D_hcmp0N_offset_p<5>'             0; ...
           53 1 'D_hcmp0N_offset_p<6>'             0; ...
           53 0 'D_hcmp0N_offset_p<7>'             0; ...
           
           52 7 'D_hcmp0N_offset_p<8>'             0; ...
           52 6 'D_hcmp0N_offset_p<9>'             0; ...
           52 5 'D_hcmp0N_offset_p<10>'            0; ...
           52 4 'D_hcmp0N_offset_p<11>'            0; ...
           52 3 'D_hcmp0N_offset_p<12>'            0; ...
           52 2 'D_hcmp0N_offset_m<0>'             0; ...
           52 1 'D_hcmp0N_offset_m<1>'             0; ...
           52 0 'D_hcmp0N_offset_m<2>'             0; ...
           
           51 7 'D_hcmp0N_offset_m<3>'             0; ...
           51 6 'D_hcmp0N_offset_m<4>'             0; ...
           51 5 'D_hcmp0N_offset_m<5>'             0; ...
           51 4 'D_hcmp0N_offset_m<6>'             0; ...
           51 3 'D_hcmp0N_offset_m<7>'             0; ...
           51 2 'D_hcmp0N_offset_m<8>'             0; ...
           51 1 'D_hcmp0N_offset_m<9>'             0; ...
           51 0 'D_hcmp0N_offset_m<10>'            0; ...
           
           50 7 'D_hcmp0N_offset_m<11>'            0; ...
           50 6 'D_hcmp0N_offset_m<12>'            0; ...
           50 5 'D_hdac_decreaseRange_m<5>'        0; ...
           50 4 'D_hdac_decreaseRange_m<4>'        0; ...
           50 3 'D_hdac_decreaseRange_m<3>'        0; ...
           50 2 'D_hdac_decreaseRange_m<2>'        0; ...
           50 1 'D_hdac_decreaseRange_m<1>'        0; ...
           50 0 'D_hdac_decreaseRange_m<0>'        0; ...
           
           49 7 'D_hdac_calWord1_m<3>'             0; ...
           49 6 'D_hdac_calWord1_m<4>'             0; ...
           49 5 'D_hdac_calWord1_m<5>'             0; ...
           49 4 'D_hdac_calWord1_m<6>'             0; ...
           49 3 'D_hdac_calWord1_m<7>'             0; ...
           49 2 'D_hdac_calWord1_m<8>'             0; ...
           49 1 'D_hdac_calWord1_m<9>'             0; ...
           49 0 'D_hdac_calWord0_m<0>'             0; ...
           
           48 7 'D_hdac_calWord0_m<1>'             0; ...
           48 6 'D_hdac_calWord0_m<2>'             0; ...
           48 5 'D_hdac_calWord0_m<3>'             0; ...
           48 4 'D_hdac_calWord0_m<4>'             0; ...
           48 3 'D_hdac_calWord0_m<5>'             0; ...
           48 2 'D_hdac_calWord0_m<6>'             0; ...
           48 1 'D_hdac_calWord0_m<7>'             0; ...
           48 0 'D_hdac_calWord0_m<8>'             0; ...
           
           47 7 'D_hdac_calWord0_m<9>'             0; ...
           47 6 'D_hdac_caux_earlyDisconnect'      0; ...
           47 5 'D_hdac_caux_disable'              0; ...
           47 4 'D_hdac_creset_disable'            0; ...
           47 3 'D_href_bypass'                    0; ... % in schematic D_hdac_caux_spare<22>
           47 2 'D_hdac_caux_spare<21>'            0; ...
           47 1 'D_hdac_caux_spare<20>'            0; ...
           47 0 'D_hdac_caux_spare<19>'            0; ...
           
           46 7 'D_hdac_caux_spare<18>'            0; ...
           46 6 'D_hdac_caux_spare<17>'            0; ...
           46 5 'D_hdac_caux_spare<16>'            0; ...
           46 4 'D_hdac_caux_spare<15>'            0; ...
           46 3 'D_hdac_caux_spare<14>'            0; ...
           46 2 'D_hdac_caux_spare<13>'            0; ...
           46 1 'D_hdac_caux_spare<12>'            0; ...
           46 0 'D_hdac_caux_spare<11>'            0; ...
           
           45 7 'D_hdac_caux_spare<10>'            0; ...
           45 6 'D_hdac_caux_spare<9>'             0; ...
           45 5 'D_hdac_caux_spare<8>'             0; ...
           45 4 'D_hdac_caux_spare<7>'             0; ...
           45 3 'D_hdac_caux_spare<6>'             0; ...
           45 2 'D_hdac_caux_spare<5>'             0; ...
           45 1 'D_hdac_caux_spare<4>'             0; ...
           45 0 'D_hdac_caux_spare<3>'             0; ...
           
           44 7 'D_hdac_caux_spare<2>'             0; ...
           44 6 'D_hdac_caux_spare<1>'             0; ...
           44 5 'D_hdac_caux_spare<0>'             0; ...
           44 4 'D_qdacC_calWord0_m<7>'            0; ...
           44 3 'D_qdacC_calWord0_m<6>'            0; ...
           44 2 'D_qdacC_calWord0_m<5>'            0; ...
           44 1 'D_qdacC_calWord0_m<4>'            0; ...
           44 0 'D_qdacC_calWord0_m<3>'            0; ...
           
           43 7 'D_qdacC_calWord0_m<2>'            0; ...
           43 6 'D_qdacC_calWord0_m<1>'            0; ...
           43 5 'D_qdacC_calWord0_m<0>'            0; ...
           43 4 'D_qdacC_calWord1_m<7>'            0; ...
           43 3 'D_qdacC_calWord1_m<6>'            0; ...
           43 2 'D_qdacC_calWord1_m<5>'            0; ...
           43 1 'D_qdacC_calWord1_m<4>'            0; ...
           43 0 'D_qdacC_calWord1_m<3>'            0; ...
           
           42 7 'D_qdacC_decreaseRange_m<0>'       0; ...
           42 6 'D_qdacC_decreaseRange_m<1>'       0; ...
           42 5 'D_qdacC_decreaseRange_m<2>'       0; ...
           42 4 'D_qdacC_decreaseRange_m<3>'       0; ...
           42 3 'D_qdacC_decreaseRange_m<4>'       0; ...
           42 2 'D_qdacC_decreaseRange_m<5>'       0; ...
           42 1 'D_qdacC_calWord1_m<2>'            0; ...
           42 0 'D_qdacC_calWord1_m<1>'            0; ...
           
           41 7 'D_qdacC_calWord1_m<0>'            0; ...
           41 6 'D_qdacC_calWord2_m<7>'            0; ...
           41 5 'D_qdacC_calWord2_m<6>'            0; ...
           41 4 'D_qdacC_calWord2_m<5>'            0; ...
           41 3 'D_qdacC_calWord2_m<4>'            0; ...
           41 2 'D_qdacC_calWord2_m<3>'            0; ...
           41 1 'D_qdacC_calWord2_m<2>'            0; ...
           41 0 'D_qdacC_calWord2_m<1>'            0; ...
           
           40 7 'D_qdacC_calWord2_m<0>'            0; ...
           40 6 'D_qdacC_calMode_m'                0; ...
           40 5 'D_qdacC_decreaseBW_m<0>'          0; ...
           40 4 'D_qdacC_decreaseBW_m<1>'          0; ...
           40 3 'D_qdacC_decreaseBW_m<2>'          0; ...
           40 2 'D_qdacC_decreaseBW_m<3>'          0; ...
           40 1 'D_qdacC_decreaseBW_m<4>'          0; ...
           40 0 'D_qdacC_decreaseBW_m<5>'          0; ...
           
           39 7 'D_share_dacC_m'                   0; ...
           39 6 'D_qcmp1_threshold<8>'             0; ...
           39 5 'D_qcmp1_threshold<7>'             0; ...
           39 4 'D_qcmp1_threshold<6>'             0; ...
           39 3 'D_qcmp1_threshold<5>'             0; ...
           39 2 'D_qcmp1_threshold<4>'             0; ...
           39 1 'D_qcmp1_threshold<3>'             0; ...
           39 0 'D_qcmp1_threshold<2>'             0; ...
           
           38 7 'D_qcmp1_threshold<1>'             0; ...
           38 6 'D_qcmp1_threshold<0>'             0; ...
           38 5 'D_qcmp1_offset<8>'                0; ...
           38 4 'D_qcmp1_offset<7>'                0; ...
           38 3 'D_qcmp1_offset<6>'                0; ...
           38 2 'D_qcmp1_offset<5>'                0; ...
           38 1 'D_qcmp1_offset<4>'                0; ...
           38 0 'D_qcmp1_offset<3>'                0; ...
           
           37 7 'D_qcmp1_offset<2>'                0; ...
           37 6 'D_qcmp1_offset<1>'                0; ...
           37 5 'D_qcmp1_offset<0>'                0; ...
           37 4 'D_qcmp1_ctrl<2>'                  0; ...
           37 3 'D_qcmp1_ctrl<1>'                  0; ...
           37 2 'D_qcmp1_ctrl<0>'                  0; ...
           37 1 'D_qcmp0_ctrl<0>'                  0; ...
           37 0 'D_qcmp0_ctrl<1>'                  0; ...
           
           36 7 'D_qcmp0_ctrl<2>'                  0; ...
           36 6 'D_qcmp0_offset<0>'                0; ...
           36 5 'D_qcmp0_offset<1>'                0; ...
           36 4 'D_qcmp0_offset<2>'                0; ...
           36 3 'D_qcmp0_offset<3>'                0; ...
           36 2 'D_qcmp0_offset<4>'                0; ...
           36 1 'D_qcmp0_offset<5>'                0; ...
           36 0 'D_qcmp0_offset<6>'                0; ...
           
           35 7 'D_qcmp0_offset<7>'                0; ...
           35 6 'D_qcmp0_offset<8>'                0; ...
           35 5 'D_qcmp0_threshold<0>'             0; ...
           35 4 'D_qcmp0_threshold<1>'             0; ...
           35 3 'D_qcmp0_threshold<2>'             0; ...
           35 2 'D_qcmp0_threshold<3>'             0; ...
           35 1 'D_qcmp0_threshold<4>'             0; ...
           35 0 'D_qcmp0_threshold<5>'             0; ...
           
           34 7 'D_qcmp0_threshold<6>'             0; ...
           34 6 'D_qcmp0_threshold<7>'             0; ...
           34 5 'D_qcmp0_threshold<8>'             0; ...
           34 4 'D_qcmp0_threshold<9>'             0; ...
           34 3 'D_qcmp0_threshold<10>'            0; ...
           34 2 'D_qcmp0_threshold<11>'            0; ...
           34 1 'D_qcmp0_threshold<12>'            0; ...
           34 0 'D_qcmp2_offset<5>'                0; ...
           
           33 7 'D_qcmp2_offset<6>'                0; ...
           33 6 'D_qcmp2_offset<7>'                0; ...
           33 5 'D_qcmp2_offset<8>'                0; ...
           33 4 'D_qcmp2_threshold<0>'             0; ...
           33 3 'D_qcmp2_threshold<1>'             0; ...
           33 2 'D_qcmp2_threshold<2>'             0; ...
           33 1 'D_qcmp2_threshold<3>'             0; ...
           33 0 'D_qcmp2_threshold<4>'             0; ...
           
           32 7 'D_qcmp2_threshold<5>'             0; ...
           32 6 'D_qcmp2_threshold<6>'             0; ...
           32 5 'D_qcmp2_threshold<7>'             0; ...
           32 4 'D_qcmp2_threshold<8>'             0; ...
           32 3 'D_qcmp2_threshold<9>'             0; ...
           32 2 'D_qcmp2_threshold<10>'            0; ...
           32 1 'D_qcmp2_threshold<11>'            0; ...
           32 0 'D_qcmp2_threshold<12>'            0; ...
           
           31 7 'D_qcmp3_threshold<12>'            0; ...
           31 6 'D_qcmp3_threshold<11>'            0; ...
           31 5 'D_qcmp3_threshold<10>'            0; ...
           31 4 'D_qcmp3_threshold<9>'             0; ...
           31 3 'D_qcmp3_threshold<8>'             0; ...
           31 2 'D_qcmp3_threshold<7>'             0; ...
           31 1 'D_qcmp3_threshold<6>'             0; ...
           31 0 'D_qcmp3_threshold<5>'             0; ...
           
           30 7 'D_qcmp3_threshold<4>'             0; ...
           30 6 'D_qcmp3_threshold<3>'             0; ...
           30 5 'D_qcmp3_threshold<2>'             0; ...
           30 4 'D_qcmp3_threshold<1>'             0; ...
           30 3 'D_qcmp3_threshold<0>'             0; ...
           30 2 'D_qcmp3_offset<8>'                0; ...
           30 1 'D_qcmp3_offset<7>'                0; ...
           30 0 'D_qcmp3_offset<6>'                0; ...
           
           29 7 'D_qcmp3_offset<5>'                0; ...
           29 6 'D_qcmp3_offset<4>'                0; ...
           29 5 'D_qcmp3_offset<3>'                0; ...
           29 4 'D_qcmp3_offset<2>'                0; ...
           29 3 'D_qcmp3_offset<1>'                0; ...
           29 2 'D_qcmp3_offset<0>'                0; ...
           29 1 'D_qcmp3_ctrl<2>'                  0; ...
           29 0 'D_qcmp3_ctrl<1>'                  0; ...
           
           28 7 'D_qcmp3_ctrl<0>'                  0; ...
           28 6 'D_qcmp2_ctrl<0>'                  0; ...
           28 5 'D_qcmp2_ctrl<1>'                  0; ...
           28 4 'D_qcmp2_ctrl<2>'                  0; ...
           28 3 'D_qcmp2_offset<0>'                0; ...
           28 2 'D_qcmp2_offset<1>'                0; ...
           28 1 'D_qcmp2_offset<2>'                0; ...
           28 0 'D_qcmp2_offset<3>'                0; ...
           
           27 7 'D_qcmp2_offset<4>'                0; ...
           27 6 'D_qdacF_decreaseBW_m<5>'          0; ...
           27 5 'D_qdacF_decreaseBW_m<4>'          0; ...
           27 4 'D_qdacF_decreaseBW_m<3>'          0; ...
           27 3 'D_qdacF_decreaseBW_m<2>'          0; ...
           27 2 'D_qdacF_decreaseBW_m<1>'          0; ...
           27 1 'D_qdacF_decreaseBW_m<0>'          0; ...
           27 0 'D_qdacF_calMode_m'                0; ...
           
           26 7 'D_qdacF_calWord2_m<0>'            0; ...
           26 6 'D_qdacF_calWord2_m<1>'            0; ...
           26 5 'D_qdacF_calWord2_m<2>'            0; ...
           26 4 'D_qdacF_calWord2_m<3>'            0; ...
           26 3 'D_qdacF_calWord2_m<4>'            0; ...
           26 2 'D_qdacF_calWord2_m<5>'            0; ...
           26 1 'D_qdacF_calWord2_m<6>'            0; ...
           26 0 'D_qdacF_calWord2_m<7>'            0; ...
           
           25 7 'D_qdacF_calWord1_m<0>'            0; ...
           25 6 'D_qdacF_calWord1_m<1>'            0; ...
           25 5 'D_qdacF_calWord1_m<2>'            0; ...
           25 4 'D_precharge<0>'                   0; ...
           25 3 'D_precharge<1>'                   0; ...
           25 2 'D_precharge<2>'                   0; ...
           25 1 'D_hdac_flash_m'                   0; ...
           25 0 'D_hcmp0P_offset_p<0>'             0; ...
           
           24 7 'D_hcmp0P_offset_p<1>'             0; ...
           24 6 'D_hcmp0P_offset_p<2>'             0; ...
           24 5 'D_hcmp0P_offset_p<3>'             0; ...
           24 4 'D_hcmp0P_offset_p<4>'             0; ...
           24 3 'D_hcmp0P_offset_p<5>'             0; ...
           24 2 'D_hcmp0P_offset_p<6>'             0; ...
           24 1 'D_hcmp0P_offset_p<7>'             0; ...
           24 0 'D_hcmp0P_offset_p<8>'             0; ...
           
           23 7 'D_hcmp0P_offset_p<9>'             0; ...
           23 6 'D_hcmp0P_offset_p<10>'            0; ...
           23 5 'D_hcmp0P_offset_p<11>'            0; ...
           23 4 'D_hcmp0P_offset_p<12>'            0; ...
           23 3 'D_hcmp0P_offset_m<0>'             0; ...
           23 2 'D_hcmp0P_offset_m<1>'             0; ...
           23 1 'D_hcmp0P_offset_m<2>'             0; ...
           23 0 'D_hcmp0P_offset_m<3>'             0; ...
           
           22 7 'D_hcmp0P_offset_m<4>'             0; ...
           22 6 'D_hcmp0P_offset_m<5>'             0; ...
           22 5 'D_hcmp0P_offset_m<6>'             0; ...
           22 4 'D_hcmp0P_offset_m<7>'             0; ...
           22 3 'D_hcmp0P_offset_m<8>'             0; ...
           22 2 'D_hcmp0P_offset_m<9>'             0; ...
           22 1 'D_hcmp0P_offset_m<10>'            0; ...
           22 0 'D_hcmp0P_offset_m<11>'            0; ...
           
           21 7 'D_hcmp0P_offset_m<12>'            0; ...
           21 6 'D_hdac_decreaseBW_m<5>'           0; ...
           21 5 'D_hdac_decreaseBW_m<4>'           0; ...
           21 4 'D_hdac_decreaseBW_m<3>'           0; ...
           21 3 'D_hdac_decreaseBW_m<2>'           0; ...
           21 2 'D_hdac_decreaseBW_m<1>'           0; ...
           21 1 'D_hdac_decreaseBW_m<0>'           0; ...
           21 0 'D_hdac_calMode_m'                 0; ...
           
           20 7 'D_hdac_calWord2_m<0>'             0; ...
           20 6 'D_hdac_calWord2_m<1>'             0; ...
           20 5 'D_hdac_calWord2_m<2>'             0; ...
           20 4 'D_hdac_calWord2_m<3>'             0; ...
           20 3 'D_hdac_calWord2_m<4>'             0; ...
           20 2 'D_hdac_calWord2_m<5>'             0; ...
           20 1 'D_hdac_calWord2_m<6>'             0; ...
           20 0 'D_hdac_calWord2_m<7>'             0; ...
           
           19 7 'D_hdac_calWord2_m<8>'             0; ...
           19 6 'D_hdac_calWord2_m<9>'             0; ...
           19 5 'D_hdac_calWord1_m<0>'             0; ...
           19 4 'D_hdac_calWord1_m<1>'             0; ...
           19 3 'D_hdac_calWord1_m<2>'             0; ...
           19 2 'NC'                               0; ...
           19 1 'NC'                               0; ...
           19 0 'NC'                               0; ...
           
           18 7 'NC'                               0; ...
           18 6 'NC'                               0; ...
           18 5 'NC'                               0; ...
           18 4 'NC'                               0; ...
           18 3 'NC'                               0; ...
           18 2 'NC'                               0; ...
           18 1 'NC'                               0; ...
           18 0 'NC'                               0; ...
           
           17 7 'NC'                               0; ...
           17 6 'NC'                               0; ...
           17 5 'NC'                               0; ...
           17 4 'NC'                               0; ...
           17 3 'NC'                               0; ...
           17 2 'NC'                               0; ...
           17 1 'NC'                               0; ...
           17 0 'NC'                               0; ...
           
           16 7 'NC'                               0; ...
           16 6 'NC'                               0; ...
           16 5 'NC'                               0; ...
           16 4 'NC'                               0; ...
           16 3 'NC'                               0; ...
           16 2 'NC'                               0; ...
           16 1 'NC'                               0; ...
           16 0 'NC'                               0; ...
           
           15 7 'NC'                               0; ...
           15 6 'NC'                               0; ...
           15 5 'NC'                               0; ...
           15 4 'NC'                               0; ...
           15 3 'NC'                               0; ...
           15 2 'NC'                               0; ...
           15 1 'NC'                               0; ...
           15 0 'NC'                               0; ...
           
           14 7 'NC'                               0; ...
           14 6 'NC'                               0; ...
           14 5 'NC'                               0; ...
           14 4 'NC'                               0; ...
           14 3 'NC'                               0; ...
           14 2 'NC'                               0; ...
           14 1 'NC'                               0; ...
           14 0 'NC'                               0; ...
           
           13 7 'NC'                               0; ...
           13 6 'NC'                               0; ...
           13 5 'NC'                               0; ...
           13 4 'NC'                               0; ...
           13 3 'NC'                               0; ...
           13 2 'NC'                               0; ...
           13 1 'NC'                               0; ...
           13 0 'NC'                               0; ...
           
           12 7 'NC'                               0; ...
           12 6 'NC'                               0; ...
           12 5 'NC'                               0; ...
           12 4 'NC'                               0; ...
           12 3 'NC'                               0; ...
           12 2 'NC'                               0; ...
           12 1 'NC'                               0; ...
           12 0 'NC'                               0; ...
           
           11 7 'NC'                               0; ...
           11 6 'NC'                               0; ...
           11 5 'NC'                               0; ...
           11 4 'NC'                               0; ...
           11 3 'NC'                               0; ...
           11 2 'NC'                               0; ...
           11 1 'NC'                               0; ...
           11 0 'NC'                               0; ...
           
           10 7 'NC'                               0; ...
           10 6 'NC'                               0; ...
           10 5 'NC'                               0; ...
           10 4 'NC'                               0; ...
           10 3 'NC'                               0; ...
           10 2 'NC'                               0; ...
           10 1 'NC'                               0; ...
           10 0 'NC'                               0; ...
           
            9 7 'NC'                               0; ...
            9 6 'NC'                               0; ...
            9 5 'NC'                               0; ...
            9 4 'NC'                               0; ...
            9 3 'NC'                               0; ...
            9 2 'NC'                               0; ...
            9 1 'NC'                               0; ...
            9 0 'NC'                               0; ...
            
            8 7 'NC'                               0; ...
            8 6 'NC'                               0; ...
            8 5 'NC'                               0; ...
            8 4 'NC'                               0; ...
            8 3 'NC'                               0; ...
            8 2 'NC'                               0; ...
            8 1 'NC'                               0; ...
            8 0 'NC'                               0; ...
            
            7 7 'NC'                               0; ...
            7 6 'NC'                               0; ...
            7 5 'NC'                               0; ...
            7 4 'NC'                               0; ...
            7 3 'NC'                               0; ...
            7 2 'NC'                               0; ...
            7 1 'NC'                               0; ...
            7 0 'NC'                               0; ...
            
            6 7 'NC'                               0; ...
            6 6 'NC'                               0; ...
            6 5 'NC'                               0; ...
            6 4 'NC'                               0; ...
            6 3 'NC'                               0; ...
            6 2 'NC'                               0; ...
            6 1 'NC'                               0; ...
            6 0 'NC'                               0; ...
            
            5 7 'NC'                               0; ...
            5 6 'NC'                               0; ...
            5 5 'NC'                               0; ...
            5 4 'NC'                               0; ...
            5 3 'NC'                               0; ...
            5 2 'NC'                               0; ...
            5 1 'NC'                               0; ...
            5 0 'NC'                               0; ...
            
            4 7 'NC'                               0; ...
            4 6 'NC'                               0; ...
            4 5 'NC'                               0; ...
            4 4 'NC'                               0; ...
            4 3 'NC'                               0; ...
            4 2 'NC'                               0; ...
            4 1 'NC'                               0; ...
            4 0 'NC'                               0; ...
            
            3 7 'NC'                               0; ...
            3 6 'NC'                               0; ...
            3 5 'NC'                               0; ...
            3 4 'NC'                               0; ...
            3 3 'NC'                               0; ...
            3 2 'NC'                               0; ...
            3 1 'NC'                               0; ...
            3 0 'NC'                               0; ...
            
            2 7 'NC'                               0; ...
            2 6 'NC'                               0; ...
            2 5 'NC'                               0; ...
            2 4 'NC'                               0; ...
            2 3 'NC'                               0; ...
            2 2 'NC'                               0; ...
            2 1 'NC'                               0; ...
            2 0 'NC'                               0; ...
            
            1 7 'NC'                               0; ...
            1 6 'NC'                               0; ...
            1 5 'NC'                               0; ...
            1 4 'NC'                               0; ...
            1 3 'NC'                               0; ...
            1 2 'NC'                               0; ...
            1 1 'NC'                               0; ...
            1 0 'NC'                               0; ...
            
            0 7 'NC'                               0; ...
            0 6 'NC'                               0; ...
            0 5 'NC'                               0; ...
            0 4 'NC'                               0; ...
            0 3 'NC'                               0; ...
            0 2 'NC'                               0; ...
            0 1 'NC'                               0; ...
            0 0 'NC'                               0};

end